import { AI_CRAWLERS } from './crawlers'
import { generateRobotsTxt } from './generators'
import { describe, expect, test } from 'bun:test'

describe('generateRobotsTxt', () => {
  test('default output blocks all AI_CRAWLERS', () => {
    const output = generateRobotsTxt()
    for (const crawler of AI_CRAWLERS) {
      expect(output).toContain(`User-agent: ${crawler.userAgent}`)
      expect(output).toContain('Disallow: /')
    }
  })

  test('allows Googlebot and Bingbot', () => {
    const output = generateRobotsTxt()
    expect(output).toContain('User-agent: Googlebot\nAllow: /')
    expect(output).toContain('User-agent: Bingbot\nAllow: /')
    // They should not appear in a Disallow block
    const disallowBlocks = output.split('\n').reduce<string[][]>((acc, line) => {
      if (line.startsWith('User-agent:')) acc.push([line])
      else if (acc.length) acc[acc.length - 1].push(line)
      return acc
    }, [])
    const blocked = disallowBlocks.filter((b) => b.some((l) => l === 'Disallow: /')).map((b) => b[0])
    expect(blocked.some((l) => l.includes('Googlebot'))).toBe(false)
    expect(blocked.some((l) => l.includes('Bingbot'))).toBe(false)
  })

  test('blockAll: false produces no crawler blocks', () => {
    const output = generateRobotsTxt({ blockAll: false })
    expect(output).not.toContain('Disallow: /')
  })

  test('block: [GPTBot] only blocks GPTBot', () => {
    const output = generateRobotsTxt({ block: ['GPTBot'] })
    const disallowSections = output.split('\n\n').filter((s) => s.includes('Disallow: /'))
    expect(disallowSections).toHaveLength(1)
    expect(disallowSections[0]).toContain('User-agent: GPTBot')
  })

  test('allow: [ClaudeBot] removes ClaudeBot from the block list', () => {
    const output = generateRobotsTxt({ allow: ['ClaudeBot'] })
    // ClaudeBot should not be blocked
    const lines = output.split('\n')
    const claudeIdx = lines.indexOf('User-agent: ClaudeBot')
    if (claudeIdx !== -1) {
      expect(lines[claudeIdx + 1]).not.toBe('Disallow: /')
    }
    // Other crawlers should still be blocked
    expect(output).toContain('User-agent: GPTBot')
  })

  test('block + allow together works', () => {
    const output = generateRobotsTxt({ block: ['GPTBot', 'ClaudeBot'], allow: ['ClaudeBot'] })
    const disallowSections = output.split('\n\n').filter((s) => s.includes('Disallow: /'))
    expect(disallowSections).toHaveLength(1)
    expect(disallowSections[0]).toContain('User-agent: GPTBot')
    expect(output).not.toMatch(/User-agent: ClaudeBot\nDisallow: \//)
  })

  test('customRules appears in output after crawler rules', () => {
    const custom = 'User-agent: *\nCrawl-delay: 10'
    const output = generateRobotsTxt({ customRules: custom })
    expect(output).toContain(custom)
    const crawlerEnd = output.lastIndexOf('Allow: /')
    const customStart = output.indexOf(custom)
    expect(customStart).toBeGreaterThan(crawlerEnd)
  })

  test('sitemap appears at the end', () => {
    const output = generateRobotsTxt({ sitemap: 'https://example.com/sitemap.xml' })
    expect(output).toContain('Sitemap: https://example.com/sitemap.xml')
    expect(output.trimEnd().endsWith('Sitemap: https://example.com/sitemap.xml')).toBe(true)
  })

  test('contains the Obscrd header comment', () => {
    const output = generateRobotsTxt()
    expect(output).toContain('# Generated by Obscrd')
  })
})
