import { AI_CRAWLERS } from './crawlers'

export interface RobotsOptions {
  /** Block all AI crawlers (default: true) */
  blockAll?: boolean
  /** Specific crawlers to block (overrides blockAll) */
  block?: string[]
  /** Specific crawlers to allow */
  allow?: string[]
  /** Additional custom rules */
  customRules?: string
  /** Sitemap URL */
  sitemap?: string
}

/**
 * Generate a robots.txt string that blocks AI crawlers
 */
export function generateRobotsTxt(options: RobotsOptions = {}): string {
  const { blockAll = true, block, allow, customRules, sitemap } = options

  // ── Determine which crawlers to block ──

  let crawlers = block
    ? AI_CRAWLERS.filter((c) => block.some((b) => b === c.name || b === c.userAgent))
    : blockAll
      ? AI_CRAWLERS
      : []

  if (allow?.length) {
    crawlers = crawlers.filter((c) => !allow.some((a) => a === c.name || a === c.userAgent))
  }

  // ── Build output ──

  const lines: string[] = ['# Generated by Obscrd (https://obscrd.dev)', '# Block AI training crawlers', '']

  for (const crawler of crawlers) {
    lines.push(`User-agent: ${crawler.userAgent}`)
    lines.push('Disallow: /')
    lines.push('')
  }

  lines.push('# Allow traditional search engines')
  lines.push('User-agent: Googlebot')
  lines.push('Allow: /')
  lines.push('')
  lines.push('User-agent: Bingbot')
  lines.push('Allow: /')

  if (customRules) {
    lines.push('')
    lines.push(customRules)
  }

  if (sitemap) {
    lines.push('')
    lines.push(`Sitemap: ${sitemap}`)
  }

  return lines.join('\n')
}
