import { AI_CRAWLERS } from './crawlers'

export interface RobotsOptions {
  /** Block all AI crawlers (default: true) */
  blockAll?: boolean
  /** Specific crawlers to block (overrides blockAll) */
  block?: string[]
  /** Specific crawlers to allow */
  allow?: string[]
  /** Additional custom rules */
  customRules?: string
  /** Sitemap URL */
  sitemap?: string
}

/**
 * Generate a robots.txt string that blocks AI crawlers
 */
export function generateRobotsTxt(options: RobotsOptions = {}): string {
  // TODO: Implement full generator
  const { blockAll = true, sitemap } = options
  const crawlers = blockAll ? AI_CRAWLERS : []

  const lines: string[] = ['# Generated by Obscrd (https://obscrd.dev)', '# Block AI training crawlers', '']

  for (const crawler of crawlers) {
    lines.push(`User-agent: ${crawler.userAgent}`)
    lines.push('Disallow: /')
    lines.push('')
  }

  lines.push('# Allow traditional search engines')
  lines.push('User-agent: Googlebot')
  lines.push('Allow: /')
  lines.push('')
  lines.push('User-agent: Bingbot')
  lines.push('Allow: /')

  if (sitemap) {
    lines.push('')
    lines.push(`Sitemap: ${sitemap}`)
  }

  return lines.join('\n')
}
